# Generated by Django 4.2.16 on 2024-09-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eco_guia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='history_images/')),
                ('last_classified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
