# Generated by Django 4.2.16 on 2024-09-30 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eco_guia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cardboard', 'Cardboard'), ('glass', 'Glass'), ('metal', 'Metal'), ('paper', 'Paper'), ('plastic', 'Plastic'), ('trash', 'Trash')], max_length=100)),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(upload_to='history_images/')),
                ('last_classified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='app_eco_gui_categor_38e464_idx'), models.Index(fields=['last_classified'], name='app_eco_gui_last_cl_7cc3c8_idx')],
                'unique_together': {('category', 'image')},
            },
        ),
    ]
