# Generated by Django 4.2.16 on 2024-10-04 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_eco_guia', '0002_imagehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RECLAMACOES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnome', models.CharField(max_length=100)),
                ('remail', models.EmailField(max_length=254, unique=True)),
                ('mensagem', models.CharField(max_length=2000)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamacoes', to='app_eco_guia.usuario')),
            ],
        ),
    ]
