# Generated by Django 5.1.1 on 2024-09-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eco_guia', '0002_imagehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageHistory',
        ),
    ]
