# Generated by Django 4.2.16 on 2024-09-27 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eco_guia', '0002_imagehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehistory',
            name='category',
            field=models.CharField(choices=[('cardboard', 'Cardboard'), ('glass', 'Glass'), ('metal', 'Metal'), ('paper', 'Paper'), ('plastic', 'Plastic'), ('trash', 'Trash')], max_length=100),
        ),
        migrations.AlterField(
            model_name='imagehistory',
            name='count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='imagehistory',
            unique_together={('category', 'image')},
        ),
        migrations.AddIndex(
            model_name='imagehistory',
            index=models.Index(fields=['category'], name='app_eco_gui_categor_38e464_idx'),
        ),
        migrations.AddIndex(
            model_name='imagehistory',
            index=models.Index(fields=['last_classified'], name='app_eco_gui_last_cl_7cc3c8_idx'),
        ),
    ]
