# Generated by Django 4.2.16 on 2024-10-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eco_guia', '0003_reclamacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacoes',
            name='remail',
            field=models.EmailField(max_length=254),
        ),
    ]
