# Generated by Django 4.2.16 on 2024-10-05 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_eco_guia', '0004_alter_reclamacoes_remail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORIAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categ', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IDEIAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.CharField(max_length=6000)),
                ('id_categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eco_guia.categorias')),
            ],
        ),
    ]
