# Generated by Django 4.2.16 on 2024-10-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eco_guia', '0005_categorias_ideias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CATEGORIAS',
            new_name='CATEGORIA',
        ),
        migrations.RenameModel(
            old_name='IDEIAS',
            new_name='IDEIA',
        ),
        migrations.RenameModel(
            old_name='RECLAMACOES',
            new_name='RECLAMACOE',
        ),
    ]
