# Generated by Django 4.2.16 on 2024-10-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eco_guia', '0006_rename_categorias_categoria_rename_ideias_ideia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideia',
            name='resumo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
