# Generated by Django 4.2.16 on 2024-11-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eco_guia', '0007_ideia_resumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tipo_material', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='imagehistory',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
