# Generated by Django 4.2.16 on 2024-11-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eco_guia', '0008_marcadores_alter_imagehistory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehistory',
            name='category',
            field=models.CharField(choices=[('casca_de_ovo', 'Casca de Ovo'), ('lixo', 'Lixo'), ('metal', 'Metal'), ('papel', 'Papel'), ('plastico', 'Plastico'), ('residuo_de_alimentos', 'Residuo de Alimentos'), ('vidro', 'Vidro')], max_length=100),
        ),
    ]
